### ISSUE TITLE
Question about branchexecext

### ISSUE THREAD

**Issue by PhilippeOlivier** [scipopt/PySCIPOpt#436] opened 2020-09-28 18:55 UTC
I am solving a problem via branch and price, and I need to do three-way branching similar to what the `branchexecext` callback does. The [SCIP documentation](https://www.scipopt.org/doc-5.0.0/html/BRANCH.php) mentions that

> The BRANCHEXECEXT callback is executed during node processing if no LP solution is available and the list of external branching candidates is not empty.

And further says that

> In contrast to the LP branching candidates and the pseudo branching candidates, the list of external branching candidates will not be generated automatically. The user has to add all variables to the list by calling SCIPaddExternBranchCand() for each of them. Usually, this will happen in the execution method of a relaxation handler or in the enforcement methods of a constraint handler.

If my understanding is correct I should add external candicates in the `consenfolp` function. I am not sure how to do that since the Python interface does not seem to offer a mechanism similar to `SCIPaddExternBranchCand()`.

Thanks for your time.

**Comment by fserra** [comment] 2020-10-05 13:33
If you a function that is not currently supported you can extend the interface to include the function, see https://github.com/SCIP-Interfaces/PySCIPOpt#extending-the-interface.

However, the `branchexecext` callback doesn't branch 3-way by itself. SCIP has different branching rules, e.g. relpscost, pscost, inference, etc. They may or may not implement the `branchexecext` and they may or may not do 3-way branching.

The external candidates are just variables that somebody (usually a constraint handler) said that it might be interesting to branch on them. However, it doesn't specify how and the branching rule might do whatever it wants.

If you want to implement a particular type of branching for your problem I think the best is that you implement your own branching rule. So it might make more sense to have a look at https://www.scipopt.org/doc/html/BRANCH.php#BRANCHEXECLP

**Comment by PhilippeOlivier** [comment] 2020-10-16 14:10
Thank you for the pointers. I'm honestly having a hard time wrapping my head around SCIP's branching/constraint handler mechanics. I will explain what we are trying to do and maybe you can clarify some things for me.

We are solving a problem via branch and price, and when we reach an integer solution, we need to check that this solution is feasible according to a certain constraint which we can't directly embed in the column generation/branch-and-price model itself. Basically, we take the integer solution, construct a graph from it, and check if a Hamiltonian path exists in that graph. If one exists, then the solution is feasible, otherwise it is infeasible. If the solution is infeasible, what we want to do instead of pruning this node is to do 3-way branching on an integer variable in that solution (e.g., if some variable x has value 3, we want to branch on x<=2, x==3, x>=4).

To get the basics of this working, I wrote a small example using a different problem. I merged the two examples cutstock.py and test_branch_probing_lp.py to have a working branch-and-price for this bin packing problem. Instead of checking for a Hamiltonian path in an integer solution, the feasibility criterion will be that each variable in an integer solution must have a value that is a multiple of 10, otherwise the integer solution is infeasible.

My understanding of the Branchrule/Conshdlr mechanics is as follows:
- If a node has some fractional variables, then branchexeclp() is called.
- If a node does not have any fractional variables, then branchexecps() is called.
- When we reach a fractional solution, consenfolp() is called. We will say that all fractional solutions are feasible since we are interested in checking the feasibility of integer solutions only.
- When we branch on a pseudo-solution, which is integral (right?), consenfops() is called. This is the place where we want to make sure that the value of each variable is a multiple of 10.
- We never seem to be able to branch on pseudo-solutions.

Here is the example in question (PS: I extended the Python interface to have access to getPseudoBranchCands(), but since we never branch on pseudo-solutions, I commented out that function below so it can be run directly):

```
from pyscipopt import *

try:
    from types import SimpleNamespace
except:
    class SimpleNamespace:
        def __init__(self, **kwargs):
            self.__dict__.update(kwargs)

        def __repr__(self):
            keys = sorted(self.__dict__)
            items = ("{}={!r}".format(k, self.__dict__[k]) for k in keys)
            return "{}({})".format(type(self).__name__, ", ".join(items))

        def __eq__(self, other):
            return self.__dict__ == other.__dict__

class MustEndInZeroConshdlr(Conshdlr):
    def consenfolp(self, constraints, nusefulconss, solinfeasible):
        print('===> Entering consenfolp()')
        # print(constraints[0].data.model.getStatus())
        return {"result": SCIP_RESULT.FEASIBLE}

    def consenfops(self, constraints, nusefulconss, solinfeasible, objinfeasible):
        print("===> Entering consenfops()")
        assert False, 'This is never called because branchexecps() is never called?'
        return {}

    def conscheck(self, constraints, solution, checkintegrality, checklprows, printreason, completely):
        print("===> Entering conscheck()")
        assert len(constraints) == 1
        # status = constraints[0].data.model.getStatus()
        # print(f'Solution status: {status}')
        return {"result": SCIP_RESULT.FEASIBLE}

    def conspresol(self, constraints, nrounds, presoltiming,
                   nnewfixedvars, nnewaggrvars, nnewchgvartypes, nnewchgbds, nnewholes,
                   nnewdelconss, nnewaddconss, nnewupgdconss, nnewchgcoefs, nnewchgsides, result_dict):
        return result_dict

class CutBranching(Branchrule):
    def __init__(self, model, variables):
        self.model = model
        self.variables = variables

    def branchexeclp(self, allowaddcons):
        print('===> Entering branchexeclp()')
        # print(f'Choices: {self.model.getLPBranchCands()}')
        choice = self.model.getLPBranchCands()[0][0]
        down, eq, up = self.model.branchVar(choice)
        # print('Branching on', choice)
        return {"result": SCIP_RESULT.BRANCHED}

    def branchexecps(self, alloaddcons):
        print('===> Entering branchexecps()')
        assert False, 'This is never called!'
        # print(f'Choices: {[(i, i.getLPSol()) for i in self.model.getPseudoBranchCands()[0]]}')
        # choice = self.model.getPseudoBranchCands()[0][0]
        # down, eq, up = self.model.branchVar(choice)
        # print('Branching on', choice)
        return {"result": SCIP_RESULT.BRANCHED}
    
class CutPricer(Pricer):
    def __init__(self):
        self.data = {}

    def pricerinit(self):
        for i, c in enumerate(self.data['cons']):
            self.data['cons'][i] = self.model.getTransformedCons(c)
        
    def pricerredcost(self):
        dualSolutions = []
        for i, c in enumerate(self.data['cons']):
            dualSolutions.append(self.model.getDualsolLinear(c))

        # Building a MIP to solve the subproblem
        subMIP = Model("CuttingStock-Sub")
        subMIP.setPresolve(SCIP_PARAMSETTING.OFF)
        subMIP.hideOutput()

        # Variables for subMIP
        cutWidthVars = []
        varNames = []
        varBaseName = "CutWidth"
        for i in range(len(dualSolutions)):
            varNames.append(varBaseName + "_" + str(i))
            cutWidthVars.append(subMIP.addVar(varNames[i], vtype = "I", obj = -1.0 * dualSolutions[i]))

        # Adding the knapsack constraint (pricing problem constraints)
        knapsackCons = subMIP.addCons(
            quicksum(w*v for (w,v) in zip(self.data['widths'], cutWidthVars)) <= self.data['rollLength'])

        # Solving the subMIP to generate the most negative reduced cost pattern
        subMIP.optimize()

        # Adding a new column to the master problem
        objval = 1 + subMIP.getObjVal()
        if objval < -1e-08:
            currentNumVar = len(self.data['var'])
            newVar = self.model.addVar("NewPattern_" + str(currentNumVar), vtype="I", obj=1.0, pricedVar=True)
            newPattern = []
            for i, c in enumerate(self.data['cons']):
                coeff = round(subMIP.getVal(cutWidthVars[i]))
                self.model.addConsCoeff(c, newVar, coeff)
                newPattern.append(coeff)

            # Storing the new variable in the pricer data.
            self.data['patterns'].append(newPattern)
            self.data['var'].append(newVar)
            print(f'==========> Generated a column: NewPattern_{currentNumVar}')

        return {'result':SCIP_RESULT.SUCCESS}

def cuttingstock():
    # Master problem
    s = Model("CuttingStock")
    s.setPresolve(0)

    # Pricing problem
    pricer = CutPricer()
    s.includePricer(pricer, "CuttingStockPricer", "Pricer to identify new cutting stock patterns")

    # Problem data
    widths = [14, 31, 36, 45]
    demand = [211, 395, 610, 97]
    rollLength = 100

    # MP variables
    cutPatternVars = []
    varNames = []
    varBaseName = "Pattern"
    patterns = []

    # Initial columns: Variables
    for i in range(len(widths)):
        varNames.append(varBaseName + "_" + str(i))
        cutPatternVars.append(s.addVar(varNames[i], obj = 1.0, vtype = "I"))

    # Demand constraints
    demandCons = []
    for i in range(len(widths)):
        numWidthsPerRoll = float(int(rollLength/widths[i]))
        demandCons.append(s.addCons(numWidthsPerRoll*cutPatternVars[i] >= demand[i], separate = False, modifiable = True))
        newPattern = [0]*len(widths)
        newPattern[i] = numWidthsPerRoll
        patterns.append(newPattern)

    # Setting the pricer_data for use in the init and redcost functions
    pricer.data['var'] = cutPatternVars
    pricer.data['cons'] = demandCons
    pricer.data['widths'] = widths
    pricer.data['demand'] = demand
    pricer.data['rollLength'] = rollLength
    pricer.data['patterns'] = patterns

    # Add the branching rule to the MP
    branchrule = CutBranching(s, cutPatternVars)
    s.includeBranchrule(branchrule, '', '', priority=1, maxdepth=65534, maxbounddist=1.0)

    conshdlr = MustEndInZeroConshdlr()
    s.includeConshdlr(conshdlr, "", "", enfopriority = 10, chckpriority = 10)
    cons = s.createCons(conshdlr, "", modifiable=True, local=True)
    cons.data = SimpleNamespace()
    cons.data.vars = cutPatternVars
    cons.data.model = s
    s.addPyCons(cons)
    
    # solve problem
    s.optimize()

    # print original data
    printWidths = '\t'.join(str(e) for e in widths)
    print('\nInput Data')
    print('==========')
    print('Roll Length:', rollLength)
    print('Widths:\t', printWidths)
    print('Demand:\t', '\t'.join(str(e) for e in demand))

    # print solution
    widthOutput = [0]*len(widths)
    print('\nResult')
    print('======')
    print('\t\tSol Value', '\tWidths\t', printWidths)
    for i in range(len(pricer.data['var'])):
        rollUsage = 0
        solValue = s.getVal(pricer.data['var'][i])
        if solValue > 0:
            outline = 'Pattern_' + str(i) + ':\t' + str(solValue) + '\t\tCuts:\t '
            for j in range(len(widths)):
                rollUsage += pricer.data['patterns'][i][j]*widths[j]
                widthOutput[j] += pricer.data['patterns'][i][j]*solValue
                outline += str(pricer.data['patterns'][i][j]) + '\t'
            outline += 'Usage:' + str(rollUsage)
            print(outline)

    print('\t\t\tTotal Output:\t', '\t'.join(str(e) for e in widthOutput))
    
if __name__ == '__main__':
    cuttingstock()
```

**Comment by fserra** [comment] 2020-10-21 18:31
Hi.

I will try to explain a bit what SCIP does, but I don't understand everything, so I will omit some parts. So what I say next is very roughly what goes on.

After the lp is solved and cuts have been added, the constraints are asked to enforce a solution.
So the `consenfolp` callback is called (usually).  Whether the `consenfolp` or `consefops` callback is called depends on whether the LP was solved in the current node.

Now, there is a constraint that enforces integrality, `cons_integral`. In its enforcement, it will call the branching methods via `SCIPbranchLP` which will call the `branchexeclp` callback of the branching rule **if** there are fractional variables.
(This is why, when you create a constraint handler with enfo priority negative (the enfo priority of `cons_integral` is 0) its enforcement method will only receive integer solutions)

Now, if some constraint is infeasible but nobody could resolve the infeasibility (either by cutting or branching or whatnot), then SCIP is going to try to branch. First it tries again branching on the LP solution. Then it tries branching on the external candidates (e.g. nonlinear constraints can say they are infeasible but inform SCIP that it can branch on some of the variables of the nonlinear constraint).
If this fails, it will try branching on the pseudo solution (i.e. `branchexecps` is called). In this callback one is supposed to branch on the variables returned by `SCIPgetPseudoBranchCands` which are the unfixed variables. The pseudosolution is just assigning the variable to its best bound w.r.t to the objective coefficient. So, yes, it is integral for integer variables.

So:

> If a node has some fractional variables, then branchexeclp() is called.

probably, if no constraint handler with a higher priority than `cons_integral` resolves the infeasibility first

> If a node does not have any fractional variables, then branchexecps() is called.

Not necessarily. First the constraints need to be enforced and if no one resolves the infeasibility, then branching on the external candidates is tried first. Only then, it seems, that `branchexecps`
is called.


So looking at your code:

* You should print the statistics at the end `s.printStatistics()`. There you can observe that your branching rule is never called. The problem is that its priority is very small. So you should do something like:
```python
    s.includeBranchrule(branchrule, 'CutBranch', '', priority=100000, maxdepth=65534, maxbounddist=1.0)
```

* Your constraint handler is not enforcing any constraint, it just says feasible.
So it is reasonable to expect that the `branchexecps` is never called.
I guess you want to only check integer feasible solutions, so you should set its priority and check priority to a negative number like
```
    s.includeConshdlr(conshdlr, "Div10", "", enfopriority = -10, chckpriority = -10)
```
I guess you also need the following code in the enfolp and enfops
```python
        s = self.model
        vars = s.getVars()
        for v in vars:
            if s.getSolVal(None, v) % 10 != 0:
                return {"result": SCIP_RESULT.INFEASIBLE}

        return {"result": SCIP_RESULT.FEASIBLE}
```
and
```python
        s = self.model
        vars = s.getVars()
        for v in vars:
            if s.getSolVal(solution, v) % 10 != 0:
                return {"result": SCIP_RESULT.INFEASIBLE}

        return {"result": SCIP_RESULT.FEASIBLE}
```
in `conscheck`.

Then you also probably need to cutoff the node when all variables are fixed and they are not divisible by 10.

**Comment by ssriram1992** [comment] 2020-10-23 11:34
@fserra Thanks for the above. I am trying to do the last step that you have mentioned: i.e., cut off the node when all variables are fixed by the following code in consenfolp. 

My idea is --- if all variables are fixed (i.e., UB - LB <= 0.5), and the problem is infeasible, then we can return `SCIP_RESULT.CUTOFF` else we just return `SCIP_RESULT.INFEASIBLE`. 

But the solver seems to be stuck in some infinite loop. Am I doing it correctly; is it expected to work?
```Python
def consenfolp(self, constraints, nusefulconss, solinfeasible):
    '''calls enforcing method of constraint handler for LP solution for all constraints added'''
    if VERBOSE >= DEBUG:
        print("****************** CONSENFOLP")
    # print('solution is:', [constraints[0].data.model.getVal(i) for i in constraints[0].data.vars])
    # We assume that any LP solution is feasible, since infeasibility is determined only once all variables are integer
    s = self.model
    nodeDiscard = True
    var =  s.getVars()
    for v in var:
        if v.getUbLocal() - v.getLbLocal() > 0.5:
            nodeDiscard = False
    if VERBOSE >= DEBUG:
        print("Discardable node found")
    for v in var:
        if s.getSolVal(None, v) % 10 !=0:
            if nodeDiscard:
                return {"result": SCIP_RESULT.CUTOFF}
            else:
                return {"result": SCIP_RESULT.INFEASIBLE}

    return {"result": SCIP_RESULT.FEASIBLE}
```

**Comment by fserra** [comment] 2020-10-26 14:43
Hey @ssriram1992 
I don't think you are in an infinite loop. I think the issue is that your variables are unbounded. Also, when you do `s.getVars()` this is getting the original variables. So the new patterns that you are generating are not being checked. You need to use `s.getVars(transformed=True)`, but it will still not solve the instance I guess...

**Closed** 2021-06-28 09:13 UTC
