### ISSUE TITLE
about getLPColsData and getLPRowsData etc. return NULL

### ISSUE THREAD

**Issue by Liwow** [scipopt/PySCIPOpt#818] opened 2024-03-18 09:20 UTC
Dear: 
This is my code. I test a CapacitatedFacilityLocation generated by Ecole default 
`    model.readProblem('./instance/train/CF/CF_0.lp')
    model.setPresolve(SCIP_PARAMSETTING.FAST)

    model.optimize()
    # return correctly
    if model.getStatus() == "optimal":
        print("Optimal value:", model.getObjVal())
        vars = model.getVars()
        for var in vars:
            val = model.getVal(var)
            print(f"Variable {var.name} has value {val}")
        print(model.getBestSol())

    print('------------------------------------------------')
    # something wrong
    cols = model.getLPColsData()
    ncols = model.getNLPCols()
    rows = model.getLPRowsData()
    print(ncols)  # return 0
    print(cols)   # return []
    print(rows)     # return []`
I use PySCIPOpt 5.0.0 and SCIP 9.0.0
I want to know return [] is normal or what wrong with this test. I want to retrieve the cols.

**Comment by Joao-Dionisio** [comment] 2024-03-18 10:13
Hey @Liwow! Can you send the instance, please? 

Maybe SCIP's presolving solves the model right away? But also, I think the ```getLPColsData```, etc., refer to the current linear relaxation of a problem, and can only be called while the problem is being solved. In the SCIP documentation [link](https://scipopt.org/doc/html/group__PublicLPMethods.php#gac09084135572e531028e3e942ee52bde) it says that these function can only be called in ```SCIP_STAGE_SOLVING```.

Maybe what you can do is let SCIP know that this is actually an LP, and so instead of doing ```from pyscipopt import Model```, do ```from pyscipopt import LP```, and then you can use the methods from here: [LP documentation](https://scipopt.github.io/PySCIPOpt/docs/html/namespacepyscipopt_1_1lp.html). This might be better suited for what you want.

(I am not sure whether there's a much easier way to do this).

**Comment by Liwow** [comment] 2024-03-18 12:05
Thanks for replying!
I have uploaded an instance in the attachment.
[CF_0.txt](https://github.com/scipopt/PySCIPOpt/files/14635896/CF_0.txt)
 I understand what's you mean and what happened due to your explain. 
I have also tried `model.setPresolve(SCIP_PARAMSETTING.OFF)` . But it also return null.
Unfortunately, this is a MIP problem. So LP is not work. But thank you very much for your explanation. I will try to 
find alternative solutions to solve it.

**Comment by abb-omidi** [comment] 2024-03-19 13:01
@Liwow,

As far as I know, the only way to do what you are looking for is to define a separation callback and execute the methods like `m.getLPSolstat()` or `m.isLPSolBasic()`. 

Then actually define or workaround with:

```
cols = m.getLPColsData()
rows = m.getLPRowsData()
bases = m.getLPBasisInd()
```
and call them in a separation callback as:

`model.includeSepa(separation(), "...", "...", , ,) `

I hope that someone on the SCIP side if has another idea, shares that.

Best

**Comment by Liwow** [comment] 2024-03-19 13:21
@abb-omidi Thanks for replying!
I agree that it can only be executed during a callback. And it seems to be no other way.

**Comment by leoneifler** [comment] 2024-03-22 08:19
Yeah, at the point where you are calling these methods, there is no LP anymore since the solving process is finished. You write that the purpose is to see what is wrong with the test. What does the SCIP output say?

**Comment by Joao-Dionisio** [comment] 2024-05-05 09:21
I'm closing this issue to clear the issue page @Liwow, but feel free to reopen if you're still having problems!

**Closed** 2024-05-05 09:20 UTC
