### ISSUE TITLE
writing several .sol/.lp/.log to file within loop leads to -> ERROR: cannot create file .... Too many open files

### ISSUE THREAD

**Issue by JPelda** [scipopt/PySCIPOpt#542] opened 2021-11-14 19:04 UTC
File "src\pyscipopt\scip.pyx", line 1387, in pyscipopt.scip.Model.writeProblem
  File "src\pyscipopt\scip.pyx", line 239, in pyscipopt.scip.PY_SCIP_CALL
OSError: SCIP: cannot create file!

I found in a forum that I would have to change the allowed maximum of simulatiously opened files.  However, it might be better to close opened files after writing to them anyway. The error happens after writing 83 .sol files but my simulation is going to produce 8759 of those solution files. Any idea to get this working?

I appreciate any help! And thank you very much for your work on pyscipopt!

Best
Johannes

**Comment by JPelda** [comment] 2021-11-17 13:02
With new version pyscipopt 3.4 it seems to work although the windows explorer stops working. Closing file descriptor is a good choice!

**Comment by CGraczyk** [comment] 2022-02-16 11:19
```
line 70, in <module>
    scip.writeStatistics()
  File "src/pyscipopt/scip.pyx", line 4612, in pyscipopt.scip.Model.writeStatistics
OSError: [Errno 9] Bad file descriptor
```
model.writeStatistics() is failing - seems to be introduced by #543, ideas @mattmilten ?

**Comment by mattmilten** [comment] 2022-03-26 12:42
I honestly don't know how to resolve that issue. On the one hand, we cannot close the file explicitly (see #570), still there are apparently some dangling file descriptors flying around.

**Comment by Joao-Dionisio** [comment] 2024-06-21 10:30
I'm closing this issue for now, since it's quite old and I wasn't able to reproduce it in version 9.0.1. Both in Linux and Windows I was able to write 1000 .sol files. Maybe something got fixed along the way. But of course, feel free to reopen if you're still having problems or concerns.

**Closed by Joao-Dionisio** 2024-06-21 10:30 UTC
Labels: bug
