### ISSUE TITLE
TrySol crashes in CustomHeuristic

### ISSUE THREAD

**Issue by MattAlexMiracle** [scipopt/PySCIPOpt#719] opened 2023-08-17 16:00 UTC
Hello, I'm trying to write a heuristic that fixes variables according to pre-existing variable assignments: Basically I have a method A that solves a variation of the problem, which produces solutions that are usually compatible with the full problem B.
To "add in" variables that have changed, I simply fix all known variables in probing mode, solve the LP, and apply the solution if the problem is consistent to problem B:

```py
class MyHeur(Heur):
    def __init__(self,data):
        print("new heuristic with",len(data),"options")
        self.data = data

    def heurexec(self, heurtiming, nodeinfeasible):
        print("running Heuristic....")
        accepted = False
        for d in self.data:
            m=self.model
            self.model.startProbing()
            #m = Model(sourceModel=self.model.__repr__.__self__)
            for v in m.getVars():
                if v.getLbLocal() + 0.5 > v.getUbLocal():
                    continue
                value = d.get(str(v),None)
                if value is not None:
                    m.fixVarProbing(v,value)
            m.propagateProbing(20)
            print("propagation done")
            m.constructLP()
            lperror, cutoff = m.solveProbingLP(10000)
            print("solver done with error",lperror, "cutoff?",cutoff)
            # now check feasibility
            if cutoff or lperror:
                m.endProbing()
                continue
            print("getting best solution")
            sol = self.model.getBestSol()
            print("Stage:",self.model.getStage()==SCIP_STAGE.SOLVING)
            
            accepted = self.model.trySol(sol)
            print("now end solution",accepted)
            m.endProbing()
            #if not a:
            #    self.model.freeSol(sol)
            if accepted:
                break

        if accepted:
            return {"result": SCIP_RESULT.FOUNDSOL}
        else:
            return {"result": SCIP_RESULT.DIDNOTFIND}
```
The code runs fine up until `print("Stage:",self.model.getStage()==SCIP_STAGE.SOLVING)` where it also verifies that it is in the solving stage. However, it then crashes when appying the solution using `trySol`.
Am I doing something wrong?

I'm using linux with kernel `6.4.8-arch1-1` with conda

**Comment by Joao-Dionisio** [comment] 2023-08-17 17:16
Hello, @MattAlexMiracle! I think the problem here is that ```trySol``` requires that you set a value for every variable of the problem. However, the solution provided by the LP has some variables fixed, meaning that that solution cannot be directly applied to the original model. You need to modify the solution to include the fixed variables as well, by using ```self.model.setSolVal(sol,...,...)```.

I'm sorry if I didn't understand your problem, but please let me know if this helped! You also have Issue #487 which may have more information.

**Comment by MattAlexMiracle** [comment] 2023-08-17 17:58
Thank you for your quick response: I looked at #487 before and didn't find it to work. Specifically when ammeding my code such that it sets the values of fixed variables
```py

class MyHeur(Heur):
    def __init__(self,data):
        print("new heuristic with",len(data),"options")
        self.data = data

    def heurexec(self, heurtiming, nodeinfeasible):
        print("running Heuristic....")
        accepted = False
        for d in self.data:
            m=self.model
            self.model.startProbing()
            #m = Model(sourceModel=self.model.__repr__.__self__)
            for v in m.getVars():
                """if v.getLbLocal() + 0.5 > v.getUbLocal():
                    continue"""
                value = d.get(str(v),None)
                if value is not None:
                    print("setting var",v,"to",value)
                    m.fixVarProbing(v,value)
            m.propagateProbing(20)
            print("propagation done")
            m.constructLP()
            lperror, cutoff = m.solveProbingLP(10000)
            print("solver done with error",lperror, "cutoff?",cutoff)
            # now check feasibility
            if cutoff or lperror:
                m.endProbing()
                continue
            print("getting best solution")
            sol = self.model.getBestSol()
            print("Stage:",self.model.getStage()==SCIP_STAGE.SOLVING)
            for v in m.getVars():
                value = d.get(str(v),None)
                if value is not None:
                    print("adding in var", str(v))  
                    print("current value",sol[v])
                    m.setSolVal(sol,v,value)
                    print("out")
            print("solution built")
            accepted = self.model.trySol(sol)
            print("now end solution",accepted)
            m.endProbing()
            #if not a:
            #    self.model.freeSol(sol)
            if accepted:
                break

        if accepted:
            return {"result": SCIP_RESULT.FOUNDSOL}
        else:
            return {"result": SCIP_RESULT.DIDNOTFIND}
```
It instantly crashes for `m.setSolVal(sol,v,value)`.
Further, I don't believe the call is necessary in the first place: If I look at `sol[v]`right before attempting to set the variable, it already produces a value (sometimes nonzero, so shouldn't be a default). If I comment out the variable setting  line `m.setSolVal(sol,v,value)` it also runs through the entire variable set before crashing at trySol again.

**Comment by Joao-Dionisio** [comment] 2023-08-29 11:32
Oh man, I'm sorry @MattAlexMiracle, I forgot about this... Would you mind sending a minimal reproducible example my way, so that I can try to figure out wat's going wrong?

**Comment by MattAlexMiracle** [comment] 2023-08-29 17:07
No problem:

```py
from pyscipopt import Model, quicksum, SCIP_RESULT,quickprod, SCIP_PARAMSETTING
from pyscipopt import Model, Heur, SCIP_RESULT, SCIP_PARAMSETTING, SCIP_HEURTIMING, SCIP_STAGE
import numpy as np


class MyHeur(Heur):
    def __init__(self,data):
        self.data = data

    def heurexec(self, heurtiming, nodeinfeasible):
        print("running Heuristic....")
        accepted = False
        for d in self.data:
            m=self.model
            self.model.startProbing()
            #m = Model(sourceModel=self.model.__repr__.__self__)
            for v in m.getVars():
                value = d.get(str(v),None)
                if value is not None:
                    #print("setting var",v,"to",value)
                    m.fixVarProbing(v,value)
            m.propagateProbing(20)
            m.constructLP()
            lperror, cutoff = m.solveProbingLP(10000)
            # now check feasibility
            if cutoff or lperror:
                m.endProbing()
                continue
            sol = self.model.getBestSol()
            for v in m.getVars():
                value = d.get(str(v),None)
                if value is not None:
                    print("current value of fixed variable", str(v), "is", value)
            print("crashing here")
            accepted = self.model.trySol(sol)
            print("never reaches this")
            m.endProbing()
            if accepted:
                break

        if accepted:
            return {"result": SCIP_RESULT.FOUNDSOL}
        else:
            return {"result": SCIP_RESULT.DIDNOTFIND}


def make_problem(size1, size2):
    model = Model()
    vars = {(i,j): model.addVar(vtype="B", name=f'assign_{i}_{j}')
                 for i in range(size1) for j in range(size2)}
    for i in range(size1):
        model.addCons(quicksum(vars[i,j] for j in range(size2)) <= 1)
    
    model.setObjective(quicksum(np.random.randn()*v for v in vars.values()),"maximize")
    return model


def main(fr, to):
    last_solution=[]
    for i in range(fr,to):
        m = make_problem(to, i)
        # Turning off presolver so that it doesn't instantly solve the toy problem
        m.setPresolve(SCIP_PARAMSETTING.OFF)
        m.includeHeur(MyHeur(last_solution),f"InitHeur{i}",
                       "initial solution heuristic",
                        "Y",
                        timingmask=SCIP_HEURTIMING.BEFORENODE,
                        freq=0,
                        maxdepth=0)
        m.optimize()
        print("here")
        tmp=m.getSols()
        last_solution = []
        for t in tmp:
            s = dict()
            for v in m.getVars():
                s[str(v)]=m.getSolVal(t,v)
            last_solution.append(s)
            break

if __name__ == "__main__":
    main(5,10)
```
should be somewhat minimal: 
The idea is that I have some problem P that increases in complexity in such a way that I can most likely (but not always) re-use previous results.
The idea is that I re-apply `last_solution` and solve for the newly added variables.
In this toy problem I have an "at most one" constraint which gets expanded by one additional choice in every iteration (I know that in this case there are simpler ways to do this, this is just a toy for illustration).
In theory, you could always add the additional variables as zeros, so this should give a result in every case.
However, SCIP crashes once I run `trySol` in the heuristic.

**Comment by Joao-Dionisio** [comment] 2023-08-29 19:56
Thank you, @MattAlexMiracle! I just ran your file, and I think it ran without issues:

![image](https://github.com/scipopt/PySCIPOpt/assets/57299939/9d645176-588a-423d-90f5-1058796956ce)

**Comment by MattAlexMiracle** [comment] 2023-08-30 11:52
So, I've now also tried running SCIP inside a docker to reduce the possibility of my system just having issues:

```
FROM debian:bullseye
WORKDIR /code
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
	 git wget cmake g++ m4 xz-utils libgmp-dev unzip zlib1g-dev libboost-program-options-dev \
	 libboost-serialization-dev libboost-regex-dev libboost-iostreams-dev libtbb-dev libreadline-dev \
	 pkg-config git liblapack-dev libgsl-dev flex bison libcliquer-dev gfortran file dpkg-dev \
	 libopenblas-dev rpm python3-dev

COPY scipoptsuite-8.0.4.tgz scipoptsuite-8.0.4.tgz
RUN tar xzvf scipoptsuite-8.0.4.tgz
 
WORKDIR /code/scipoptsuite-8.0.4
RUN	mkdir -p build
RUN	mkdir /scip
WORKDIR	/code/scipoptsuite-8.0.4/build
RUN	cmake .. -DCMAKE_INSTALL_PREFIX=/scip -DAUTOBUILD=on &&\
	make && \
	make check
RUN	make install
ENV	SCIPOPTDIR=/scip
WORKDIR /code
RUN 	apt-get install --reinstall ca-certificates -y python3-pip python3 &&\
	pip3 install cython==0.29.36 && \
	pip3 install pytest && \
	pip3 install numpy && \
	pip3 install pyscipopt
WORKDIR /code 
COPY minimal_repro.py minimal_repro.py
```
where `minimal_repro.py`  is simply the minimal example above and folder I have the dockerfile in also contains the `scipoptsuite-8.0.4.tgz`.
Running inside this docker container still leads to problems, just that it gets past the `trySol` and then crashes once it exits the heuristic.
It also doesn't seem to find a solution to the LP (accepted is false), despite the fact that a solution should exist and should be easy to find.
![grafik](https://github.com/scipopt/PySCIPOpt/assets/25751799/6e063e40-e3fe-466d-b3d4-464820ae44e8)

**Comment by Joao-Dionisio** [comment] 2023-08-31 14:21
I'm looking at this now, @MattAlexMiracle, and it seems that the problem is in the model creation for some reason. The second time it tries to create the model, just before presolve is being disabled, the script crashes with this error: ```[scip_prob.c:2023] ERROR: invalid SCIP stage <-1095155376>```. I sometimes get an error about a heuristic not being initialized as well, but I couldn't figure out the reason...

@mattmilten, do you have any thoughts on this?

**Comment by MattAlexMiracle** [comment] 2023-09-10 19:58
Just checking in: Can I help with something?
I have no issue with trying something if I can help, I'm just not familiar with the SCIP codebase ;)

**Comment by Joao-Dionisio** [comment] 2023-09-10 21:50
Hey @MattAlexMiracle :)

I can take another look in a few days, but I don't think I have the knowledge to solve this, sorry... Maybe we can both try to figure out what's going on under the hood if you have the time.

@fserra, sorry to bother you. Do you have any thoughts on this issue?

**Comment by Joao-Dionisio** [comment] 2023-09-22 14:22
Hey @MattAlexMiracle! @mmghannam from SCIP found out that if you use ```accepted = self.model.trySol(sol,free=False)```, the code seems to run fine. At least it does in the example you provided. Does it also solve the issue in your actual code?

**Comment by MattAlexMiracle** [comment] 2023-09-24 16:35
Awesome!
It doesn't quite work for my true problem (i.e. it works a couple of times and then breaks at some point), but that's something I can deal with (this might also be a bug on my end, I have to look at this more thoroughly).
Thank you both for your time!

**Comment by Joao-Dionisio** [comment] 2023-09-24 19:17
Happy to hear it, @MattAlexMiracle! I'll be closing the issue, then, but feel free to reopen it if it turns out that this doesn't actually solve it. Cheers! :)

**Closed by Joao-Dionisio** 2023-09-24 19:17 UTC
