### ISSUE TITLE
Problem with debugging in Pycharm

### ISSUE THREAD

**Issue by jirkacigler** [scipopt/PySCIPOpt#821] opened 2024-03-19 12:56 UTC
**Describe the bug**
After upgrading SCIPOptimization suite to 9.0.0 and pyscipopt to 5.0.0., it is not possible to use the same code in debug mode in Pycharm. 
Impor of pyscipopt.Model fails with error code

**To Reproduce**
same error on different win 11 machines

**Expected behavior**

**Screenshots**
`    from pyscipopt.scip      import Model
  File "complex.pxd", line 19, in init pyscipopt.scip
  File "src\\pyscipopt\\scip.pyx", line 19, in __Pyx_PyMODINIT_FUNC PyInit_scip(void)
TypeError: 'NoneType' object is not callable
python-BaseException`

**System**
 - OS: Win 11
 - Version 5.0.0.
 - SCIP 9.0.0
 - How did you install `pyscipopt`?  based on https://github.com/scipopt/PySCIPOpt/blob/master/INSTALL.md, using pip

**Additional context**
nothing

**Comment by Joao-Dionisio** [comment] 2024-03-20 10:36
Hello, @jirkacigler! Can you please provide the code which is creating the error? Also, what happens if you run the code not using PyCharm, from the command line, for example?

**Comment by jirkacigler** [comment] 2024-03-20 21:31
Debugging crashes on importing of Model
`from pyscipopt import Model`

For example in pdb, debugging works. But in Pycharm, it fails. This is the complete error output.

`
Connected to pydev debugger (build 223.8836.43)
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2022.2.4\plugins\python\helpers\pydev\pydevd.py", line 2195, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2022.2.4\plugins\python\helpers\pydev\pydevd.py", line 2177, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\JetBrains\PyCharm 2022.2.4\plugins\python\helpers\pydev\pydevd.py", line 1489, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\JetBrains\PyCharm 2022.2.4\plugins\python\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Program Files\JetBrains\PyCharm 2022.2.4\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\dev\tuning_opt.py", line 3, in <module>
    from pyscipopt import Model
  File "C:\Program Files\Python311\Lib\site-packages\pyscipopt\__init__.py", line 23, in <module>
    from pyscipopt.scip      import Model
  File "complex.pxd", line 19, in init pyscipopt.scip
  File "src\\pyscipopt\\scip.pyx", line 19, in __Pyx_PyMODINIT_FUNC PyInit_scip(void)
TypeError: 'NoneType' object is not callable
`

**Comment by Opt-Mucca** [comment] 2024-03-21 14:08
So some minor thoughts:
- This isn't general to PyCharm (or at least I am not getting errors for PyCharm 2023 on Debian)
- The error seems to be Cython related. Can you try and run `pip install Cython==3.0.9` and then run everything again? (Alternatively if that fails try `pip install Cython==0.29`)

**Comment by NeonDactyl** [comment] 2024-03-27 18:42
I'm having a similar issue on import of Model, except I'm using VIsual Studio Code on Windows 11 with debugpy to debug.

Running the file directly from python in the terminal, with no debugger attaching, works as expected.

**Comment by banjodd** [comment] 2024-04-05 10:41
I'm facing the same issue using the Spyder IDE.

OS: Win 11
Version 5.0.0.
SCIP 8.0.4

When trying to run in debug I get the following error:


  File ~\AppData\Local\anaconda3\Lib\site-packages\spyder_kernels\customize\spyderpdb.py:900 in run
    super(SpyderPdb, self).run(cmd, globals, locals)

  File ~\AppData\Local\anaconda3\Lib\bdb.py:600 in run
    exec(cmd, globals, locals)
    
    [...]

    model = Model("Test")

  File src\\pyscipopt\\scip.pxi:1004 in pyscipopt.scip.Model.__init__

TypeError: 'NoneType' object is not callable

**Comment by PHonest** [comment] 2024-04-19 07:01
I encounter the same error

OS: macOS (ARM)
Version: 5.0.0
SCIP: 9.0.0

Furthermore, I used **conda** to install the relevant dependencies

Reproducible example:
```
from pyscipopt import Model

model = Model(" modleName ")
```

This is the produced error:
```
 File "/home/test/venv/lib/python3.12/site-packages/pyscipopt/__init__.py", line 11, in <module>
    from pyscipopt.scip      import Model
  File "complex.pxd", line 19, in init pyscipopt.scip
TypeError: 'NoneType' object is not callable
```

Please let me know whether there are further details needed to reproduce the error.

**Comment by chuzhixing** [comment] 2024-05-10 05:52
> So some minor thoughts:
> 
> * This isn't general to PyCharm (or at least I am not getting errors for PyCharm 2023 on Debian)
> * The error seems to be Cython related. Can you try and run `pip install Cython==3.0.9` and then run everything again? (Alternatively if that fails try `pip install Cython==0.29`)

here is my environment:
python: 3.8 
os: windows
scip: pyscipopt-5.0.0
ide: visual studio code 1.88

my code is
```
from pyscipopt import Model
```

I have installed `pip install Cython==3.0.9`,  `pip install Cython==0.29.21`，both of them not work。

I have tried PySCIPOpt-4.4.0, it has the same question.

**Comment by chronican** [comment] 2024-06-04 09:05
Anyone has solutions up to now?

**Comment by Opt-Mucca** [comment] 2024-06-04 09:17
@mmghannam is looking into it. I'm also trying to get the next release in order across all platforms, and maybe when that is done then this issue will just resolve itself. (Would not get too hopeful for that though)

**Comment by mmghannam** [comment] 2024-06-05 05:30
I also think that the issues are probably related to a problem with an old Cython version (similar to the one in https://github.com/pandas-dev/pandas/issues/47429). We recently updated to Cython 3, and I couldn't reproduce the buggy behavior on the master branch. This should be fixed in the next release. For now, I suggest manually installing pyscipopt following the instructions in [here](https://github.com/scipopt/PySCIPOpt/blob/master/INSTALL.md#building-everything-from-source). Hope this helps!

**Comment by Opt-Mucca** [comment] 2024-06-18 08:27
Can anyone please verify if this issue still persists for the version `5.0.1`?

**Comment by richardlevinson** [comment] 2024-06-18 17:31
I'm seeing exactly the same error using PyCharm on a MacBook running OS 13.6.7. When I run in debug mode I see this error: 

    **from pyscipopt.scip      import Model
  File "complex.pxd", line 19, in init pyscipopt.scip
  File "src/pyscipopt/scip.pyx", line 19, in __Pyx_PyMODINIT_FUNC PyInit_scip(void)
TypeError: 'NoneType' object is not callable**

I think the problem is related to this comment I found in the code where if fails:
**#execute the script (note: it's important to compile first to have the filename set in debug mode)
    exec(compile(contents+"\n", file, 'exec'), glob, loc)**

This is in the file: /PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py on line 17

But how do I do that pre-compile and what do I compile?

**Comment by paradiseland** [comment] 2024-06-19 07:08
> Can anyone please verify if this issue still persists for the version `5.0.1`?

Yes, still persists

**Comment by Opt-Mucca** [comment] 2024-06-19 09:46
I will look into this with @mmghannam next week. Sorry for this taking so long. We are a bit lost, and it's not trivial to recreate this error with the computers we have.

**Comment by harlem87** [comment] 2024-06-19 09:48
Hi guys, Anyone has solutions up to now?

**Comment by jirkacigler** [comment] 2024-06-20 11:45
> I also think that the issues are probably related to a problem with an old Cython version (similar to the one in [pandas-dev/pandas#47429](https://github.com/pandas-dev/pandas/issues/47429)). We recently updated to Cython 3, and I couldn't reproduce the buggy behavior on the master branch. This should be fixed in the next release. For now, I suggest manually installing pyscipopt following the instructions in [here](https://github.com/scipopt/PySCIPOpt/blob/master/INSTALL.md#building-everything-from-source). Hope this helps!

Building PyScipOpt from source works for newest version (5.0.1, cython 3.10), however the version in pip repository does not work.

**Comment by mmghannam** [comment] 2024-06-22 12:26
I and @Opt-Mucca looked into it, and we think the problem was caused from compiling Cython with line tracing enabled (used to compute test coverage). I'm not sure why that caused problems with debugging but we disabled it in the latest release  `5.1.1` and I tested and couldn't reproduce the problem.

Could you please check again if the problem still persists in the latest release?

**Comment by zengbin5966** [comment] 2024-06-24 06:26
> I and @Opt-Mucca looked into it, and we think the problem was caused from compiling Cython with line tracing enabled (used to compute test coverage). I'm not sure why that caused problems with debugging but we disabled it in the latest release `5.1.1` and I tested and couldn't reproduce the problem.
> 
> Could you please check again if the problem still persists in the latest release?

I tried it out, and 5.1.1 works fine in VSCode.

**Closed** 2024-06-24 14:12 UTC
