### ISSUE TITLE
Solution is not optimal with presolve

### ISSUE THREAD

**Issue by liangjs** [scipopt/PySCIPOpt#516] opened 2021-06-24 09:25 UTC
The following code produces a solution of "x=0,y=50000", which is not optimal.
This can be solved by turning off presolve.

```python
import pyscipopt

model = pyscipopt.Model()
x = model.addVar("x")
y = model.addVar("y", vtype="INTEGER")

model.addCons(2*x-y*y+1.5<=0)
model.addCons(x>=0)
model.addCons(x<=10)

model.setObjective(x+y, 'minimize')

#model.setPresolve(pyscipopt.SCIP_PARAMSETTING.OFF)

model.optimize()
sol = model.getBestSol()
print("x: {}".format(sol[x]))
print("y: {}".format(sol[y]))
```

```
feasible solution found by trivial heuristic after 0.0 seconds, objective value 5.000000e+04
presolving:
(round 1, fast)       0 del vars, 2 del conss, 0 add conss, 3 chg bounds, 0 chg sides, 0 chg coeffs, 1 upgd conss, 0 impls, 0 clqs
(round 2, fast)       1 del vars, 3 del conss, 0 add conss, 3 chg bounds, 0 chg sides, 0 chg coeffs, 1 upgd conss, 0 impls, 0 clqs
presolving (3 rounds: 3 fast, 1 medium, 1 exhaustive):
 2 deleted vars, 3 deleted constraints, 0 added constraints, 3 tightened bounds, 0 added holes, 0 changed sides, 0 changed coefficients
 0 implications, 0 cliques
Presolving Time: 0.00

SCIP Status        : problem is solved [optimal solution found]
Solving Time (sec) : 0.00
Solving Nodes      : 0
Primal Bound       : +5.00000000000000e+04 (1 solutions)
Dual Bound         : +5.00000000000000e+04
Gap                : 0.00 %
x: 0.0
y: 50000.0
```

**Comment by liangjs** [comment] 2021-06-24 12:38
I was just playing with demo code. Didn't notice it is unbounded.
scip version is 7.0.3

**Comment by CGraczyk** [comment] 2021-06-24 13:19
oh my bad i missed the variable bound, its not unbounded since 0 <= x <= 10, and x = 0, y = sqrt(1.5) should be the solution right?

```
feasible solution found by trivial heuristic after 0.0 seconds, objective value 5.000000e+04
presolving:
(round 1, fast)       0 del vars, 2 del conss, 0 add conss, 3 chg bounds, 0 chg sides, 0 chg coeffs, 1 upgd conss, 0 impls, 0 clqs
(round 2, fast)       1 del vars, 3 del conss, 0 add conss, 3 chg bounds, 0 chg sides, 0 chg coeffs, 1 upgd conss, 0 impls, 0 clqs
   Deactivated symmetry handling methods, since SCIP was built without symmetry detector (SYM=none).
presolving (3 rounds: 3 fast, 1 medium, 1 exhaustive):
 2 deleted vars, 3 deleted constraints, 0 added constraints, 3 tightened bounds, 0 added holes, 0 changed sides, 0 changed coefficients
 0 implications, 0 cliques
presolved problem has 0 variables (0 bin, 0 int, 0 impl, 0 cont) and 0 constraints
transformed objective value is always integral (scale: 1)
Presolving Time: 0.00

 time | node  | left  |LP iter|LP it/n|mem/heur|mdpt |vars |cons |rows |cuts |sepa|confs|strbr|  dualbound   | primalbound  |  gap   | compl. 
t 0.0s|     1 |     0 |     0 |     - | trivial|   0 |   0 |   0 |   0 |   0 |  0 |   0 |   0 | 0.000000e+00 | 0.000000e+00 |   0.00%| unknown

SCIP Status        : problem is solved [optimal solution found]
Solving Time (sec) : 0.00
Solving Nodes      : 1
Primal Bound       : +0.00000000000000e+00 (2 solutions)
Dual Bound         : +0.00000000000000e+00
Gap                : 0.00 %
  [quadratic] <c1>:  +2<x>[C] -<y>[I]^2 <= -1.5;
violation: right hand side is violated by 1.5
best solution is not feasible in original problem
x: 0.0
y: -0.0
```
this is what i am getting when running your code, which is still weird but also not the same for the "getBestSol()" output.

**Comment by liangjs** [comment] 2021-06-25 05:59
Notice that y should be integer, so the optimal solution is "x=0,y=2".

**Comment by KBestuzheva** [comment] 2021-07-01 10:39
This is caused by a bug in the presolving of absolute power constraints. I will be adding a fix for this into C SCIP - for now, I recommend turning this presolving off by setting the parameter 'constraints/abspower/maxprerounds' to 0.

**Closed** 2021-08-02 07:47 UTC
